# tomcat
server:
  port: 2001

# eureka
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://10.5.122.34:1001/eureka/

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

# spring
spring:
  application:
    name: config-server

  # config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/D2C-Cai/mall-config.git

  # rabbitmq
  rabbitmq:
    #host: 192.168.0.146
    host: 172.31.46.2
    port: 5672
    username: guest
    password: guest